import type { Company } from '@/entities/company';
import type { VoucherType } from '@/entities/voucher-type';
import type { Ledger } from '@/entities/ledger';
import type { AccountGroup } from '@/entities/account-group';
import type { FinancialYear } from '@/entities/financial-year';
import type { Currency, ExchangeRate } from '@/entities/currency';
import type { Voucher, CreateVoucherInput } from '@/entities/voucher';
import type {
  BalanceSheetReport,
  ProfitAndLossReport,
  TrialBalanceReport,
  CashFlowReport,
  ReceiptsAndPaymentsReport,
  DayBookReport,
  CompanyContext,
  GroupOverview,
} from '@/entities/report';
import type { OutstandingsReport } from '@/entities/outstanding';

// 1. Five Major Businesses
export const MOCK_COMPANIES: Company[] = [
  {
    id: 'biz-travkings',
    name: 'Travkings Tour and Travels',
    code: 'TRAV',
    type: 'TRADING',
    legalName: 'Travkings Tour and Travels Pvt. Ltd.',
    financialYearStart: '2026-04-01',
    financialYearEnd: '2027-03-31',
    baseCurrency: 'INR',
    country: 'IND',
    state: 'Maharashtra',
    timezone: 'Asia/Kolkata',
    status: 'ACTIVE',
    initialized: true,
    seedVersion: 6,
    currentSeedVersion: 6,
    features: { billWiseDetails: true, multiCurrency: true },
  },
  {
    id: 'biz-quinaliza',
    name: 'QuinALiza',
    code: 'QUIN',
    type: 'TRADING',
    legalName: 'QuinALiza Luxury Lifestyle LLP',
    financialYearStart: '2026-04-01',
    financialYearEnd: '2027-03-31',
    baseCurrency: 'INR',
    country: 'IND',
    state: 'Delhi',
    timezone: 'Asia/Kolkata',
    status: 'ACTIVE',
    initialized: true,
    seedVersion: 6,
    currentSeedVersion: 6,
    features: { billWiseDetails: true, multiCurrency: true },
  },
  {
    id: 'biz-kings-logistic',
    name: 'Kings Logistic',
    code: 'KLOG',
    type: 'TRADING',
    legalName: 'Kings Logistic Freight & Cargo Ltd.',
    financialYearStart: '2026-04-01',
    financialYearEnd: '2027-03-31',
    baseCurrency: 'INR',
    country: 'IND',
    state: 'Gujarat',
    timezone: 'Asia/Kolkata',
    status: 'ACTIVE',
    initialized: true,
    seedVersion: 6,
    currentSeedVersion: 6,
    features: { billWiseDetails: true, multiCurrency: true },
  },
  {
    id: 'biz-hotel-kings',
    name: 'Hotel Kings Palace',
    code: 'HKPL',
    type: 'TRADING',
    legalName: 'Hotel Kings Palace & Resorts Pvt. Ltd.',
    financialYearStart: '2026-04-01',
    financialYearEnd: '2027-03-31',
    baseCurrency: 'INR',
    country: 'IND',
    state: 'Rajasthan',
    timezone: 'Asia/Kolkata',
    status: 'ACTIVE',
    initialized: true,
    seedVersion: 6,
    currentSeedVersion: 6,
    features: { billWiseDetails: true, multiCurrency: true },
  },
  {
    id: 'biz-techkings',
    name: 'Techkings',
    code: 'TECH',
    type: 'TRADING',
    legalName: 'Techkings Digital Solutions Pvt. Ltd.',
    financialYearStart: '2026-04-01',
    financialYearEnd: '2027-03-31',
    baseCurrency: 'INR',
    country: 'IND',
    state: 'Karnataka',
    timezone: 'Asia/Kolkata',
    status: 'ACTIVE',
    initialized: true,
    seedVersion: 6,
    currentSeedVersion: 6,
    features: { billWiseDetails: true, multiCurrency: true },
  },
];

// 2. Financial Years
export function getMockFinancialYears(companyId: string): FinancialYear[] {
  return [
    {
      id: `${companyId}-fy-2026`,
      companyId,
      label: '2026',
      startDate: '2026-04-01',
      endDate: '2027-03-31',
      status: 'OPEN',
    },
    {
      id: `${companyId}-fy-2025`,
      companyId,
      label: '2025',
      startDate: '2025-04-01',
      endDate: '2026-03-31',
      status: 'CLOSED',
    },
  ];
}

// 3. Currencies
export function getMockCurrencies(companyId: string): Currency[] {
  return [
    {
      id: `${companyId}-curr-inr`,
      companyId,
      code: 'INR',
      name: 'Indian Rupee',
      symbol: '₹',
      decimalPlaces: 2,
      isActive: true,
    },
    {
      id: `${companyId}-curr-usd`,
      companyId,
      code: 'USD',
      name: 'US Dollar',
      symbol: '$',
      decimalPlaces: 2,
      isActive: true,
    },
    {
      id: `${companyId}-curr-eur`,
      companyId,
      code: 'EUR',
      name: 'Euro',
      symbol: '€',
      decimalPlaces: 2,
      isActive: true,
    },
    {
      id: `${companyId}-curr-aed`,
      companyId,
      code: 'AED',
      name: 'UAE Dirham',
      symbol: 'AED',
      decimalPlaces: 2,
      isActive: true,
    },
  ];
}

export function getMockExchangeRates(companyId: string): ExchangeRate[] {
  return [
    {
      id: 'rate-1',
      currencyId: `${companyId}-curr-usd`,
      currencyCode: 'USD',
      rate: '83.50',
      effectiveFrom: '2026-10-01',
      rateType: 'STANDARD',
    },
    {
      id: 'rate-2',
      currencyId: `${companyId}-curr-eur`,
      currencyCode: 'EUR',
      rate: '91.20',
      effectiveFrom: '2026-10-01',
      rateType: 'STANDARD',
    },
    {
      id: 'rate-3',
      currencyId: `${companyId}-curr-aed`,
      currencyCode: 'AED',
      rate: '22.75',
      effectiveFrom: '2026-10-01',
      rateType: 'STANDARD',
    },
  ];
}

// 4. Voucher Types (Supporting Payment, Receipt, Contra, Journal, Sales, Purchase)
export function getMockVoucherTypes(companyId: string): VoucherType[] {
  return [
    {
      id: `${companyId}-vt-contra`,
      companyId,
      code: 'CONTRA',
      name: 'Contra',
      category: 'CONTRA',
      numberingMethod: 'AUTO',
      numbering: {
        prefix: 'CNT-',
        suffix: '',
        numberLength: 4,
        prefillWithZero: true,
        numberFormat: 'COMPANY_PREFIXED',
        resetFrequency: 'YEARLY',
        startingNumber: 1,
      },
      isSystem: true,
      isActive: true,
      configuration: {},
    },
    {
      id: `${companyId}-vt-payment`,
      companyId,
      code: 'PAYMENT',
      name: 'Payment',
      category: 'PAYMENT',
      numberingMethod: 'AUTO',
      numbering: {
        prefix: 'PMT-',
        suffix: '',
        numberLength: 4,
        prefillWithZero: true,
        numberFormat: 'COMPANY_PREFIXED',
        resetFrequency: 'YEARLY',
        startingNumber: 1,
      },
      isSystem: true,
      isActive: true,
      configuration: {},
    },
    {
      id: `${companyId}-vt-receipt`,
      companyId,
      code: 'RECEIPT',
      name: 'Receipt',
      category: 'RECEIPT',
      numberingMethod: 'AUTO',
      numbering: {
        prefix: 'RCT-',
        suffix: '',
        numberLength: 4,
        prefillWithZero: true,
        numberFormat: 'COMPANY_PREFIXED',
        resetFrequency: 'YEARLY',
        startingNumber: 1,
      },
      isSystem: true,
      isActive: true,
      configuration: {},
    },
    {
      id: `${companyId}-vt-journal`,
      companyId,
      code: 'JOURNAL',
      name: 'Journal',
      category: 'JOURNAL',
      numberingMethod: 'AUTO',
      numbering: {
        prefix: 'JRN-',
        suffix: '',
        numberLength: 4,
        prefillWithZero: true,
        numberFormat: 'COMPANY_PREFIXED',
        resetFrequency: 'YEARLY',
        startingNumber: 1,
      },
      isSystem: true,
      isActive: true,
      configuration: {},
    },
    {
      id: `${companyId}-vt-sales`,
      companyId,
      code: 'SALES',
      name: 'Sales & Income',
      category: 'SALES',
      numberingMethod: 'AUTO',
      numbering: {
        prefix: 'INV-',
        suffix: '',
        numberLength: 4,
        prefillWithZero: true,
        numberFormat: 'COMPANY_PREFIXED',
        resetFrequency: 'YEARLY',
        startingNumber: 1,
      },
      isSystem: true,
      isActive: true,
      configuration: {},
    },
    {
      id: `${companyId}-vt-purchase`,
      companyId,
      code: 'PURCHASE',
      name: 'Purchase & Expense',
      category: 'PURCHASE',
      numberingMethod: 'AUTO',
      numbering: {
        prefix: 'PUR-',
        suffix: '',
        numberLength: 4,
        prefillWithZero: true,
        numberFormat: 'COMPANY_PREFIXED',
        resetFrequency: 'YEARLY',
        startingNumber: 1,
      },
      isSystem: true,
      isActive: true,
      configuration: {},
    },
  ];
}

// 5. Account Groups
export function getMockAccountGroups(companyId: string): AccountGroup[] {
  return [
    { id: `${companyId}-grp-assets`, companyId, code: 'ASSETS', name: 'Assets', parentId: null, nature: 'ASSET', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-curr-assets`, companyId, code: 'CURRENT_ASSETS', name: 'Current Assets', parentId: `${companyId}-grp-assets`, nature: 'ASSET', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-bank`, companyId, code: 'BANK_ACCOUNTS', name: 'Bank Accounts', parentId: `${companyId}-grp-curr-assets`, nature: 'ASSET', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-cash`, companyId, code: 'CASH_IN_HAND', name: 'Cash-in-hand', parentId: `${companyId}-grp-curr-assets`, nature: 'ASSET', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-debtors`, companyId, code: 'SUNDRY_DEBTORS', name: 'Sundry Debtors', parentId: `${companyId}-grp-curr-assets`, nature: 'ASSET', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-liab`, companyId, code: 'LIABILITIES', name: 'Liabilities', parentId: null, nature: 'LIABILITY', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-capital`, companyId, code: 'CAPITAL_ACCOUNT', name: 'Capital Account', parentId: `${companyId}-grp-liab`, nature: 'LIABILITY', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-curr-liab`, companyId, code: 'CURRENT_LIABILITIES', name: 'Current Liabilities', parentId: `${companyId}-grp-liab`, nature: 'LIABILITY', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-creditors`, companyId, code: 'SUNDRY_CREDITORS', name: 'Sundry Creditors', parentId: `${companyId}-grp-curr-liab`, nature: 'LIABILITY', groupType: 'BALANCE_SHEET', isSystem: true, isActive: true },
    { id: `${companyId}-grp-income`, companyId, code: 'INCOMES', name: 'Income', parentId: null, nature: 'INCOME', groupType: 'PROFIT_LOSS', isSystem: true, isActive: true },
    { id: `${companyId}-grp-dir-income`, companyId, code: 'DIRECT_INCOMES', name: 'Direct Incomes', parentId: `${companyId}-grp-income`, nature: 'INCOME', groupType: 'PROFIT_LOSS', isSystem: true, isActive: true },
    { id: `${companyId}-grp-indir-income`, companyId, code: 'INDIRECT_INCOMES', name: 'Indirect Incomes', parentId: `${companyId}-grp-income`, nature: 'INCOME', groupType: 'PROFIT_LOSS', isSystem: true, isActive: true },
    { id: `${companyId}-grp-exp`, companyId, code: 'EXPENSES', name: 'Expenses', parentId: null, nature: 'EXPENSE', groupType: 'PROFIT_LOSS', isSystem: true, isActive: true },
    { id: `${companyId}-grp-dir-exp`, companyId, code: 'DIRECT_EXPENSES', name: 'Direct Expenses', parentId: `${companyId}-grp-exp`, nature: 'EXPENSE', groupType: 'PROFIT_LOSS', isSystem: true, isActive: true },
    { id: `${companyId}-grp-indir-exp`, companyId, code: 'INDIRECT_EXPENSES', name: 'Indirect Expenses', parentId: `${companyId}-grp-exp`, nature: 'EXPENSE', groupType: 'PROFIT_LOSS', isSystem: true, isActive: true },
  ];
}

// 6. Ledgers
export function getMockLedgers(companyId: string): Ledger[] {
  return [
    // Bank & Cash
    {
      id: `${companyId}-led-hdfc`,
      companyId,
      accountGroupId: `${companyId}-grp-bank`,
      code: 'HDFC_BANK',
      name: 'HDFC Corporate Account',
      ledgerType: 'BANK',
      openingBalance: '48500000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: true,
      isActive: true,
    },
    {
      id: `${companyId}-led-icici`,
      companyId,
      accountGroupId: `${companyId}-grp-bank`,
      code: 'ICICI_BANK',
      name: 'ICICI Escrow Account',
      ledgerType: 'BANK',
      openingBalance: '24000000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: true,
      isActive: true,
    },
    {
      id: `${companyId}-led-sbi`,
      companyId,
      accountGroupId: `${companyId}-grp-bank`,
      code: 'SBI_BANK',
      name: 'State Bank of India Oper.',
      ledgerType: 'BANK',
      openingBalance: '15200000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: true,
      isActive: true,
    },
    {
      id: `${companyId}-led-cash`,
      companyId,
      accountGroupId: `${companyId}-grp-cash`,
      code: 'CASH',
      name: 'Cash in Hand',
      ledgerType: 'CASH',
      openingBalance: '2500000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: true,
      isActive: true,
    },
    // Revenues
    {
      id: `${companyId}-led-rev-tour`,
      companyId,
      accountGroupId: `${companyId}-grp-dir-income`,
      code: 'REV_TOUR_PACKAGES',
      name: 'Tour Packages Booking Revenue',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-rev-flight`,
      companyId,
      accountGroupId: `${companyId}-grp-dir-income`,
      code: 'REV_FLIGHT_TICKETS',
      name: 'International Airline Bookings',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-rev-freight`,
      companyId,
      accountGroupId: `${companyId}-grp-dir-income`,
      code: 'REV_LOGISTICS_FREIGHT',
      name: 'Logistics Freight & Cargo Revenue',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    // Expenses
    {
      id: `${companyId}-led-exp-salary`,
      companyId,
      accountGroupId: `${companyId}-grp-dir-exp`,
      code: 'EXP_SALARIES',
      name: 'Staff & Operations Salaries',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-exp-transport`,
      companyId,
      accountGroupId: `${companyId}-grp-dir-exp`,
      code: 'EXP_TRANSPORT_FLEET',
      name: 'Fleet Logistics & Fuel Expenses',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-exp-rent`,
      companyId,
      accountGroupId: `${companyId}-grp-indir-exp`,
      code: 'EXP_OFFICE_RENT',
      name: 'Office Lease & Facility Rent',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-exp-marketing`,
      companyId,
      accountGroupId: `${companyId}-grp-indir-exp`,
      code: 'EXP_MARKETING_ADS',
      name: 'Digital Marketing & Promotions',
      ledgerType: 'GENERAL',
      openingBalance: '0',
      openingBalanceType: 'DEBIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    // Debtors (Customers)
    {
      id: `${companyId}-led-cust-habtoor`,
      companyId,
      accountGroupId: `${companyId}-grp-debtors`,
      code: 'CUST_AL_HABTOOR',
      name: 'Al Habtoor Travels LLC',
      ledgerType: 'GENERAL',
      openingBalance: '4800000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: true,
      gstin: '27AABCT1334M1Z5',
      address: 'Suite 401, Al Habtoor Tower, Dubai',
      contactEmail: 'accounts@alhabtoor.ae',
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-cust-royal`,
      companyId,
      accountGroupId: `${companyId}-grp-debtors`,
      code: 'CUST_ROYAL_HOLIDAYS',
      name: 'Royal Holidays UK Ltd',
      ledgerType: 'GENERAL',
      openingBalance: '3200000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: true,
      address: '14 Kensington High St, London',
      contactEmail: 'finance@royalholidays.co.uk',
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-cust-apex`,
      companyId,
      accountGroupId: `${companyId}-grp-debtors`,
      code: 'CUST_APEX_LOGISTICS',
      name: 'Apex Global Logistics Corp',
      ledgerType: 'GENERAL',
      openingBalance: '5500000',
      openingBalanceType: 'DEBIT',
      maintainBillwise: true,
      gstin: '24AAACT9941K1ZP',
      address: 'Sector 5, Gandhinagar Port, Gujarat',
      contactEmail: 'billing@apexlogistics.com',
      isSystem: false,
      isActive: true,
    },
    // Creditors (Suppliers / Vendors)
    {
      id: `${companyId}-led-vend-emirates`,
      companyId,
      accountGroupId: `${companyId}-grp-creditors`,
      code: 'VEND_EMIRATES_AIR',
      name: 'Emirates Airlines B2B Corporate',
      ledgerType: 'GENERAL',
      openingBalance: '2500000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: true,
      gstin: '07AAACE0123M1Z2',
      address: 'Terminal 3 Corporate Aviation, New Delhi',
      contactEmail: 'b2bindia@emirates.com',
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-vend-marriott`,
      companyId,
      accountGroupId: `${companyId}-grp-creditors`,
      code: 'VEND_MARRIOTT_INT',
      name: 'Marriott Luxury Hotel Suites B2B',
      ledgerType: 'GENERAL',
      openingBalance: '1800000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: true,
      address: 'JW Marriott Aerocity, New Delhi',
      contactEmail: 'corporate@marriott.com',
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-vend-petro`,
      companyId,
      accountGroupId: `${companyId}-grp-creditors`,
      code: 'VEND_BHARAT_PETRO',
      name: 'Bharat Petroleum Fleet Cards',
      ledgerType: 'GENERAL',
      openingBalance: '950000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: true,
      gstin: '27AAACB2480D1ZS',
      address: 'BPCL House, Ballard Estate, Mumbai',
      contactEmail: 'fleet@bharatpetroleum.in',
      isSystem: false,
      isActive: true,
    },
    // Partner Capital (25% Equal Share)
    {
      id: `${companyId}-led-cap-p1`,
      companyId,
      accountGroupId: `${companyId}-grp-capital`,
      code: 'CAP_PARTNER_1',
      name: 'Partner 1 Capital Account (25%)',
      ledgerType: 'GENERAL',
      openingBalance: '32000000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-cap-p2`,
      companyId,
      accountGroupId: `${companyId}-grp-capital`,
      code: 'CAP_PARTNER_2',
      name: 'Partner 2 Capital Account (25%)',
      ledgerType: 'GENERAL',
      openingBalance: '32000000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-cap-p3`,
      companyId,
      accountGroupId: `${companyId}-grp-capital`,
      code: 'CAP_PARTNER_3',
      name: 'Partner 3 Capital Account (25%)',
      ledgerType: 'GENERAL',
      openingBalance: '32000000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
    {
      id: `${companyId}-led-cap-p4`,
      companyId,
      accountGroupId: `${companyId}-grp-capital`,
      code: 'CAP_PARTNER_4',
      name: 'Partner 4 Capital Account (25%)',
      ledgerType: 'GENERAL',
      openingBalance: '32000000',
      openingBalanceType: 'CREDIT',
      maintainBillwise: false,
      isSystem: false,
      isActive: true,
    },
  ];
}

// 7. Seeded Vouchers with Persistent Local Storage Layer
const VOUCHER_STORAGE_KEY = 'owm.vouchers.store';

function loadStoredVouchers(companyId: string): Voucher[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(`${VOUCHER_STORAGE_KEY}_${companyId}`);
    if (raw) return JSON.parse(raw);
  } catch {
    // fallback
  }
  return [];
}

function saveStoredVouchers(companyId: string, vouchers: Voucher[]) {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(`${VOUCHER_STORAGE_KEY}_${companyId}`, JSON.stringify(vouchers));
  } catch {
    // ignore
  }
}

export function getMockVouchers(companyId: string): Voucher[] {
  const custom = loadStoredVouchers(companyId);

  const base: Voucher[] = [
    {
      id: `${companyId}-vch-1`,
      companyId,
      voucherTypeId: `${companyId}-vt-payment`,
      voucherNumber: 'PMT-0001',
      voucherDate: '2026-10-06',
      referenceNumber: 'AIR-99214',
      narration: 'Settlement for International Flight Seat Allocations to Emirates Airlines',
      status: 'POSTED',
      amount: '2500000',
      createdBy: 'Managing Owner',
      postedAt: '2026-10-06T11:20:00.000Z',
      entries: [
        {
          id: 'ent-1-1',
          ledgerId: `${companyId}-led-vend-emirates`,
          ledgerCode: 'VEND_EMIRATES_AIR',
          debit: '2500000',
          credit: '0',
          narration: 'Payment to Emirates Airlines B2B',
        },
        {
          id: 'ent-1-2',
          ledgerId: `${companyId}-led-hdfc`,
          ledgerCode: 'HDFC_BANK',
          debit: '0',
          credit: '2500000',
          narration: 'Bank Wire Transfer via HDFC Corporate',
        },
      ],
    },
    {
      id: `${companyId}-vch-2`,
      companyId,
      voucherTypeId: `${companyId}-vt-receipt`,
      voucherNumber: 'RCT-0001',
      voucherDate: '2026-10-05',
      referenceNumber: 'HAB-INV-441',
      narration: 'Payment received for Luxury Dubai Group Tour from Al Habtoor Travels',
      status: 'POSTED',
      amount: '4800000',
      createdBy: 'Managing Owner',
      postedAt: '2026-10-05T14:40:00.000Z',
      entries: [
        {
          id: 'ent-2-1',
          ledgerId: `${companyId}-led-hdfc`,
          ledgerCode: 'HDFC_BANK',
          debit: '4800000',
          credit: '0',
          narration: 'Inward remittance received',
        },
        {
          id: 'ent-2-2',
          ledgerId: `${companyId}-led-cust-habtoor`,
          ledgerCode: 'CUST_AL_HABTOOR',
          debit: '0',
          credit: '4800000',
          narration: 'Invoice settlement',
        },
      ],
    },
    {
      id: `${companyId}-vch-3`,
      companyId,
      voucherTypeId: `${companyId}-vt-payment`,
      voucherNumber: 'PMT-0002',
      voucherDate: '2026-10-04',
      referenceNumber: 'SAL-OCT-26',
      narration: 'Staff, driver, and operations salaries disbursement for October',
      status: 'POSTED',
      amount: '1850000',
      createdBy: 'Managing Owner',
      postedAt: '2026-10-04T10:15:00.000Z',
      entries: [
        {
          id: 'ent-3-1',
          ledgerId: `${companyId}-led-exp-salary`,
          ledgerCode: 'EXP_SALARIES',
          debit: '1850000',
          credit: '0',
          narration: 'October Staff Salaries',
        },
        {
          id: 'ent-3-2',
          ledgerId: `${companyId}-led-icici`,
          ledgerCode: 'ICICI_BANK',
          debit: '0',
          credit: '1850000',
          narration: 'Direct NEFT batch transfer',
        },
      ],
    },
    {
      id: `${companyId}-vch-4`,
      companyId,
      voucherTypeId: `${companyId}-vt-sales`,
      voucherNumber: 'INV-0001',
      voucherDate: '2026-10-03',
      referenceNumber: 'ROYAL-LDN-88',
      narration: 'Tour packages billing to Royal Holidays UK Ltd for Autumn Holiday Packages',
      status: 'POSTED',
      amount: '3200000',
      createdBy: 'Managing Owner',
      postedAt: '2026-10-03T16:00:00.000Z',
      entries: [
        {
          id: 'ent-4-1',
          ledgerId: `${companyId}-led-cust-royal`,
          ledgerCode: 'CUST_ROYAL_HOLIDAYS',
          debit: '3200000',
          credit: '0',
          narration: 'Billed to Royal Holidays UK',
        },
        {
          id: 'ent-4-2',
          ledgerId: `${companyId}-led-rev-tour`,
          ledgerCode: 'REV_TOUR_PACKAGES',
          debit: '0',
          credit: '3200000',
          narration: 'Tour Package Booking Revenue',
        },
      ],
    },
    {
      id: `${companyId}-vch-5`,
      companyId,
      voucherTypeId: `${companyId}-vt-payment`,
      voucherNumber: 'PMT-0003',
      voucherDate: '2026-10-02',
      referenceNumber: 'PETRO-774',
      narration: 'Bharat Petroleum fleet diesel replenishment for luxury coach fleet',
      status: 'POSTED',
      amount: '420000',
      createdBy: 'Managing Owner',
      postedAt: '2026-10-02T12:00:00.000Z',
      entries: [
        {
          id: 'ent-5-1',
          ledgerId: `${companyId}-led-exp-transport`,
          ledgerCode: 'EXP_TRANSPORT_FLEET',
          debit: '420000',
          credit: '0',
          narration: 'Diesel fuel fill-up',
        },
        {
          id: 'ent-5-2',
          ledgerId: `${companyId}-led-hdfc`,
          ledgerCode: 'HDFC_BANK',
          debit: '0',
          credit: '420000',
          narration: 'Corporate Card auto-debit',
        },
      ],
    },
    {
      id: `${companyId}-vch-6`,
      companyId,
      voucherTypeId: `${companyId}-vt-receipt`,
      voucherNumber: 'RCT-0002',
      voucherDate: '2026-10-01',
      referenceNumber: 'APEX-CARGO-12',
      narration: 'Logistics freight charges received from Apex Global Logistics Corp',
      status: 'POSTED',
      amount: '5500000',
      createdBy: 'Managing Owner',
      postedAt: '2026-10-01T15:30:00.000Z',
      entries: [
        {
          id: 'ent-6-1',
          ledgerId: `${companyId}-led-sbi`,
          ledgerCode: 'SBI_BANK',
          debit: '5500000',
          credit: '0',
          narration: 'RTGS received into SBI',
        },
        {
          id: 'ent-6-2',
          ledgerId: `${companyId}-led-cust-apex`,
          ledgerCode: 'CUST_APEX_LOGISTICS',
          debit: '0',
          credit: '5500000',
          narration: 'Freight shipment cleared',
        },
      ],
    },
    {
      id: `${companyId}-vch-7`,
      companyId,
      voucherTypeId: `${companyId}-vt-contra`,
      voucherNumber: 'CNT-0001',
      voucherDate: '2026-09-30',
      referenceNumber: 'CHQ-001294',
      narration: 'Cash withdrawal for office petty cash from HDFC Bank',
      status: 'POSTED',
      amount: '250000',
      createdBy: 'Managing Owner',
      postedAt: '2026-09-30T10:00:00.000Z',
      entries: [
        {
          id: 'ent-7-1',
          ledgerId: `${companyId}-led-cash`,
          ledgerCode: 'CASH',
          debit: '250000',
          credit: '0',
          narration: 'Cash drawn',
        },
        {
          id: 'ent-7-2',
          ledgerId: `${companyId}-led-hdfc`,
          ledgerCode: 'HDFC_BANK',
          debit: '0',
          credit: '250000',
          narration: 'Cheque self withdrawal',
        },
      ],
    },
    {
      id: `${companyId}-vch-8`,
      companyId,
      voucherTypeId: `${companyId}-vt-payment`,
      voucherNumber: 'PMT-0004',
      voucherDate: '2026-09-28',
      referenceNumber: 'MARR-B2B-19',
      narration: 'Advance deposit for luxury suites booking to Marriott Luxury Hotels',
      status: 'POSTED',
      amount: '1800000',
      createdBy: 'Managing Owner',
      postedAt: '2026-09-28T14:15:00.000Z',
      entries: [
        {
          id: 'ent-8-1',
          ledgerId: `${companyId}-led-vend-marriott`,
          ledgerCode: 'VEND_MARRIOTT_INT',
          debit: '1800000',
          credit: '0',
          narration: 'Advance for luxury rooms',
        },
        {
          id: 'ent-8-2',
          ledgerId: `${companyId}-led-hdfc`,
          ledgerCode: 'HDFC_BANK',
          debit: '0',
          credit: '1800000',
          narration: 'Wire payment',
        },
      ],
    },
  ];

  return [...custom, ...base];
}

export function createMockVoucher(companyId: string, input: CreateVoucherInput): Voucher {
  const current = getMockVouchers(companyId);
  const nextNum = current.length + 1;
  const prefix = input.voucherTypeCode.slice(0, 3).toUpperCase();
  const voucherNumber = `${prefix}-${String(nextNum).padStart(4, '0')}`;

  const totalAmount = input.entries.reduce((acc, e) => acc + (e.debit || 0), 0);

  const newVoucher: Voucher = {
    id: `${companyId}-vch-${Date.now()}`,
    companyId,
    voucherTypeId: `${companyId}-vt-${input.voucherTypeCode.toLowerCase()}`,
    voucherNumber,
    voucherDate: input.voucherDate || new Date().toISOString().split('T')[0],
    referenceNumber: input.referenceNumber || '',
    narration: input.narration || '',
    status: 'POSTED',
    amount: String(totalAmount || 100000),
    createdBy: 'Managing Owner',
    postedAt: new Date().toISOString(),
    entries: input.entries.map((ent, idx) => ({
      id: `ent-new-${Date.now()}-${idx}`,
      ledgerId: `${companyId}-led-${ent.ledgerCode.toLowerCase()}`,
      ledgerCode: ent.ledgerCode,
      debit: String(ent.debit || 0),
      credit: String(ent.credit || 0),
      narration: ent.narration || '',
    })),
  };

  const stored = loadStoredVouchers(companyId);
  saveStoredVouchers(companyId, [newVoucher, ...stored]);
  return newVoucher;
}

// 8. Reports Mock Data
export function getMockCompanyContext(companyId: string): CompanyContext {
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2027-03-31',
    },
    difference: '0.00',
    draftVouchers: 0,
  };
}

export function getMockGroupOverview(): GroupOverview {
  return {
    totals: {
      companyCount: 5,
      inactiveCount: 0,
      openYearCount: 5,
      draftVoucherCount: 0,
      byCurrency: [
        {
          currency: 'INR',
          cashAndBank: '87700000.00',
          netProfit: '46000000.00',
        },
      ],
    },
    companies: MOCK_COMPANIES.map((biz) => ({
      companyId: biz.id,
      name: biz.name,
      code: biz.code,
      baseCurrency: biz.baseCurrency,
      status: 'ACTIVE' as const,
      financialYearId: `${biz.id}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN' as const,
      cashAndBank: biz.id === 'biz-travkings' ? '48500000.00' : '12000000.00',
      netProfit:
        biz.id === 'biz-travkings'
          ? '24000000.00'
          : biz.id === 'biz-quinaliza'
          ? '7000000.00'
          : biz.id === 'biz-kings-logistic'
          ? '5000000.00'
          : biz.id === 'biz-hotel-kings'
          ? '-4000000.00'
          : '6000000.00',
      trend: [
        { month: '2026-05-01', cashAndBank: '32000000.00', netProfit: '3500000.00' },
        { month: '2026-06-01', cashAndBank: '38000000.00', netProfit: '4000000.00' },
        { month: '2026-07-01', cashAndBank: '41000000.00', netProfit: '4200000.00' },
        { month: '2026-08-01', cashAndBank: '44500000.00', netProfit: '4500000.00' },
        { month: '2026-09-01', cashAndBank: '46200000.00', netProfit: '4800000.00' },
        { month: '2026-10-01', cashAndBank: '48500000.00', netProfit: '5000000.00' },
      ],
      draftVoucherCount: 0,
      error: null,
    })),
  };
}

export function getMockBalanceSheet(companyId: string): BalanceSheetReport {
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2026-10-07',
    },
    comparison: null,
    totals: {
      assets: '174000000.00',
      liabilities: '128000000.00',
      currentPeriodProfit: '46000000.00',
      difference: '0.00',
    },
    assets: [
      {
        kind: 'group',
        id: `${companyId}-grp-curr-assets`,
        code: 'CURRENT_ASSETS',
        name: 'Current Assets',
        debit: '174000000.00',
        credit: '0.00',
        balance: '174000000.00',
        balanceSide: 'DEBIT',
        children: [
          {
            kind: 'ledger',
            id: `${companyId}-led-hdfc`,
            code: 'HDFC_BANK',
            name: 'HDFC Corporate Account',
            debit: '48500000.00',
            credit: '0.00',
            balance: '48500000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-icici`,
            code: 'ICICI_BANK',
            name: 'ICICI Escrow Account',
            debit: '24000000.00',
            credit: '0.00',
            balance: '24000000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-sbi`,
            code: 'SBI_BANK',
            name: 'State Bank of India Operations',
            debit: '15200000.00',
            credit: '0.00',
            balance: '15200000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cash`,
            code: 'CASH',
            name: 'Cash in Hand',
            debit: '2500000.00',
            credit: '0.00',
            balance: '2500000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cust-habtoor`,
            code: 'CUST_AL_HABTOOR',
            name: 'Al Habtoor Travels LLC',
            debit: '4800000.00',
            credit: '0.00',
            balance: '4800000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cust-royal`,
            code: 'CUST_ROYAL_HOLIDAYS',
            name: 'Royal Holidays UK Ltd',
            debit: '3200000.00',
            credit: '0.00',
            balance: '3200000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cust-apex`,
            code: 'CUST_APEX_LOGISTICS',
            name: 'Apex Global Logistics Corp',
            debit: '5500000.00',
            credit: '0.00',
            balance: '5500000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-fleet`,
            code: 'FIXED_FLEET',
            name: 'Luxury Coach & Vehicle Fleet',
            debit: '70300000.00',
            credit: '0.00',
            balance: '70300000.00',
            balanceSide: 'DEBIT',
          },
        ],
      },
    ],
    liabilities: [
      {
        kind: 'group',
        id: `${companyId}-grp-capital`,
        code: 'CAPITAL_ACCOUNT',
        name: 'Capital & Equity',
        debit: '0.00',
        credit: '128000000.00',
        balance: '128000000.00',
        balanceSide: 'CREDIT',
        children: [
          {
            kind: 'ledger',
            id: `${companyId}-led-cap-p1`,
            code: 'CAP_PARTNER_1',
            name: 'Partner 1 Capital Share (25%)',
            debit: '0.00',
            credit: '32000000.00',
            balance: '32000000.00',
            balanceSide: 'CREDIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cap-p2`,
            code: 'CAP_PARTNER_2',
            name: 'Partner 2 Capital Share (25%)',
            debit: '0.00',
            credit: '32000000.00',
            balance: '32000000.00',
            balanceSide: 'CREDIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cap-p3`,
            code: 'CAP_PARTNER_3',
            name: 'Partner 3 Capital Share (25%)',
            debit: '0.00',
            credit: '32000000.00',
            balance: '32000000.00',
            balanceSide: 'CREDIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-cap-p4`,
            code: 'CAP_PARTNER_4',
            name: 'Partner 4 Capital Share (25%)',
            debit: '0.00',
            credit: '32000000.00',
            balance: '32000000.00',
            balanceSide: 'CREDIT',
          },
        ],
      },
    ],
  };
}

export function getMockProfitAndLoss(companyId: string): ProfitAndLossReport {
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2026-10-07',
    },
    comparison: null,
    totals: {
      income: '287000000.00',
      expenses: '241000000.00',
      netProfit: '46000000.00',
    },
    monthly: [
      { month: '2026-04-01', income: '38000000.00', expenses: '31000000.00', netProfit: '7000000.00' },
      { month: '2026-05-01', income: '42000000.00', expenses: '35000000.00', netProfit: '7000000.00' },
      { month: '2026-06-01', income: '45000000.00', expenses: '38000000.00', netProfit: '7000000.00' },
      { month: '2026-07-01', income: '48000000.00', expenses: '40000000.00', netProfit: '8000000.00' },
      { month: '2026-08-01', income: '52000000.00', expenses: '45000000.00', netProfit: '7000000.00' },
      { month: '2026-09-01', income: '62000000.00', expenses: '52000000.00', netProfit: '10000000.00' },
    ],
    income: [
      {
        kind: 'group',
        id: `${companyId}-grp-dir-income`,
        code: 'DIRECT_INCOMES',
        name: 'Operating & Direct Revenue',
        debit: '0.00',
        credit: '287000000.00',
        balance: '287000000.00',
        balanceSide: 'CREDIT',
        children: [
          {
            kind: 'ledger',
            id: `${companyId}-led-rev-tour`,
            code: 'REV_TOUR_PACKAGES',
            name: 'Tour Package Bookings & Safari Packages',
            debit: '0.00',
            credit: '168000000.00',
            balance: '168000000.00',
            balanceSide: 'CREDIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-rev-flight`,
            code: 'REV_FLIGHT_TICKETS',
            name: 'International Flight Ticket Commissions',
            debit: '0.00',
            credit: '69000000.00',
            balance: '69000000.00',
            balanceSide: 'CREDIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-rev-freight`,
            code: 'REV_LOGISTICS_FREIGHT',
            name: 'Logistics Freight & Cargo Shipments',
            debit: '0.00',
            credit: '50000000.00',
            balance: '50000000.00',
            balanceSide: 'CREDIT',
          },
        ],
      },
    ],
    expenses: [
      {
        kind: 'group',
        id: `${companyId}-grp-dir-exp`,
        code: 'DIRECT_EXPENSES',
        name: 'Direct Operating Expenses',
        debit: '185000000.00',
        credit: '0.00',
        balance: '185000000.00',
        balanceSide: 'DEBIT',
        children: [
          {
            kind: 'ledger',
            id: `${companyId}-led-exp-salary`,
            code: 'EXP_SALARIES',
            name: 'Operations & Ground Crew Salaries',
            debit: '124000000.00',
            credit: '0.00',
            balance: '124000000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-exp-transport`,
            code: 'EXP_TRANSPORT_FLEET',
            name: 'Fleet Logistics, Fuel & Maintenance',
            debit: '61000000.00',
            credit: '0.00',
            balance: '61000000.00',
            balanceSide: 'DEBIT',
          },
        ],
      },
      {
        kind: 'group',
        id: `${companyId}-grp-indir-exp`,
        code: 'INDIRECT_EXPENSES',
        name: 'Indirect & Administrative Overheads',
        debit: '56000000.00',
        credit: '0.00',
        balance: '56000000.00',
        balanceSide: 'DEBIT',
        children: [
          {
            kind: 'ledger',
            id: `${companyId}-led-exp-rent`,
            code: 'EXP_OFFICE_RENT',
            name: 'Head Office Lease & Regional Hub Rentals',
            debit: '32000000.00',
            credit: '0.00',
            balance: '32000000.00',
            balanceSide: 'DEBIT',
          },
          {
            kind: 'ledger',
            id: `${companyId}-led-exp-marketing`,
            code: 'EXP_MARKETING_ADS',
            name: 'Digital Advertising, Google Ads & Branding',
            debit: '24000000.00',
            credit: '0.00',
            balance: '24000000.00',
            balanceSide: 'DEBIT',
          },
        ],
      },
    ],
  };
}

export function getMockTrialBalance(companyId: string): TrialBalanceReport {
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2026-10-07',
    },
    comparison: null,
    totals: {
      openingDebit: '287000000.00',
      openingCredit: '287000000.00',
      debit: '287000000.00',
      credit: '287000000.00',
      closingDebit: '287000000.00',
      closingCredit: '287000000.00',
      difference: '0.00',
    },
    rows: [
      {
        ledgerId: `${companyId}-led-hdfc`,
        accountGroupId: `${companyId}-grp-bank`,
        code: 'HDFC_BANK',
        name: 'HDFC Corporate Account',
        openingDebit: '48500000.00',
        openingCredit: '0.00',
        debit: '48500000.00',
        credit: '0.00',
        closingDebit: '48500000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-icici`,
        accountGroupId: `${companyId}-grp-bank`,
        code: 'ICICI_BANK',
        name: 'ICICI Escrow Account',
        openingDebit: '24000000.00',
        openingCredit: '0.00',
        debit: '24000000.00',
        credit: '0.00',
        closingDebit: '24000000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-sbi`,
        accountGroupId: `${companyId}-grp-bank`,
        code: 'SBI_BANK',
        name: 'State Bank of India Operations',
        openingDebit: '15200000.00',
        openingCredit: '0.00',
        debit: '15200000.00',
        credit: '0.00',
        closingDebit: '15200000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-cash`,
        accountGroupId: `${companyId}-grp-cash`,
        code: 'CASH',
        name: 'Cash in Hand',
        openingDebit: '2500000.00',
        openingCredit: '0.00',
        debit: '2500000.00',
        credit: '0.00',
        closingDebit: '2500000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-cust-habtoor`,
        accountGroupId: `${companyId}-grp-debtors`,
        code: 'CUST_AL_HABTOOR',
        name: 'Al Habtoor Travels LLC',
        openingDebit: '4800000.00',
        openingCredit: '0.00',
        debit: '4800000.00',
        credit: '0.00',
        closingDebit: '4800000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-cust-royal`,
        accountGroupId: `${companyId}-grp-debtors`,
        code: 'CUST_ROYAL_HOLIDAYS',
        name: 'Royal Holidays UK Ltd',
        openingDebit: '3200000.00',
        openingCredit: '0.00',
        debit: '3200000.00',
        credit: '0.00',
        closingDebit: '3200000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-cust-apex`,
        accountGroupId: `${companyId}-grp-debtors`,
        code: 'CUST_APEX_LOGISTICS',
        name: 'Apex Global Logistics Corp',
        openingDebit: '5500000.00',
        openingCredit: '0.00',
        debit: '5500000.00',
        credit: '0.00',
        closingDebit: '5500000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-exp-salary`,
        accountGroupId: `${companyId}-grp-dir-exp`,
        code: 'EXP_SALARIES',
        name: 'Staff & Operations Salaries',
        openingDebit: '124000000.00',
        openingCredit: '0.00',
        debit: '124000000.00',
        credit: '0.00',
        closingDebit: '124000000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-exp-transport`,
        accountGroupId: `${companyId}-grp-dir-exp`,
        code: 'EXP_TRANSPORT_FLEET',
        name: 'Fleet Logistics & Fuel',
        openingDebit: '61000000.00',
        openingCredit: '0.00',
        debit: '61000000.00',
        credit: '0.00',
        closingDebit: '61000000.00',
        closingCredit: '0.00',
      },
      {
        ledgerId: `${companyId}-led-rev-tour`,
        accountGroupId: `${companyId}-grp-dir-income`,
        code: 'REV_TOUR_PACKAGES',
        name: 'Tour Packages Revenue',
        openingDebit: '0.00',
        openingCredit: '168000000.00',
        debit: '0.00',
        credit: '168000000.00',
        closingDebit: '0.00',
        closingCredit: '168000000.00',
      },
      {
        ledgerId: `${companyId}-led-rev-flight`,
        accountGroupId: `${companyId}-grp-dir-income`,
        code: 'REV_FLIGHT_TICKETS',
        name: 'Airline Flight Sales',
        openingDebit: '0.00',
        openingCredit: '69000000.00',
        debit: '0.00',
        credit: '69000000.00',
        closingDebit: '0.00',
        closingCredit: '69000000.00',
      },
      {
        ledgerId: `${companyId}-led-rev-freight`,
        accountGroupId: `${companyId}-grp-dir-income`,
        code: 'REV_LOGISTICS_FREIGHT',
        name: 'Logistics Freight Revenue',
        openingDebit: '0.00',
        openingCredit: '50000000.00',
        debit: '0.00',
        credit: '50000000.00',
        closingDebit: '0.00',
        closingCredit: '50000000.00',
      },
    ],
  };
}

export function getMockDayBook(companyId: string): DayBookReport {
  const vouchers = getMockVouchers(companyId);
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2026-10-07',
    },
    total: '19750000.00',
    rows: vouchers.map((v) => ({
      voucherId: v.id,
      voucherNumber: v.voucherNumber,
      voucherDate: v.voucherDate,
      voucherTypeId: v.voucherTypeId,
      voucherTypeCode: v.voucherTypeId.split('-vt-')[1]?.toUpperCase() || 'PAYMENT',
      status: 'POSTED',
      narration: v.narration,
      amount: v.amount,
    })),
  };
}

export function getMockCashFlow(companyId: string): CashFlowReport {
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2026-10-07',
    },
    comparison: null,
    openingBalance: '41700000.00',
    openingSide: 'DEBIT',
    closingBalance: '87700000.00',
    closingSide: 'DEBIT',
    monthly: [
      { month: '2026-04-01', inflow: '38000000.00', outflow: '31000000.00', netChange: '7000000.00' },
      { month: '2026-05-01', inflow: '42000000.00', outflow: '35000000.00', netChange: '7000000.00' },
      { month: '2026-06-01', inflow: '45000000.00', outflow: '38000000.00', netChange: '7000000.00' },
      { month: '2026-07-01', inflow: '48000000.00', outflow: '40000000.00', netChange: '8000000.00' },
      { month: '2026-08-01', inflow: '52000000.00', outflow: '45000000.00', netChange: '7000000.00' },
      { month: '2026-09-01', inflow: '62000000.00', outflow: '52000000.00', netChange: '10000000.00' },
    ],
    totals: {
      inflow: '287000000.00',
      outflow: '241000000.00',
      netChange: '46000000.00',
    },
    inflow: [
      {
        kind: 'ledger',
        id: `${companyId}-led-rev-tour`,
        code: 'REV_TOUR_PACKAGES',
        name: 'Tour Package Client Receipts',
        debit: '168000000.00',
        credit: '0.00',
        balance: '168000000.00',
        balanceSide: 'DEBIT',
      },
      {
        kind: 'ledger',
        id: `${companyId}-led-rev-flight`,
        code: 'REV_FLIGHT_TICKETS',
        name: 'International Flight Settlement Receipts',
        debit: '69000000.00',
        credit: '0.00',
        balance: '69000000.00',
        balanceSide: 'DEBIT',
      },
    ],
    outflow: [
      {
        kind: 'ledger',
        id: `${companyId}-led-exp-salary`,
        code: 'EXP_SALARIES',
        name: 'Staff Salaries & Operations Wages',
        debit: '0.00',
        credit: '124000000.00',
        balance: '124000000.00',
        balanceSide: 'CREDIT',
      },
      {
        kind: 'ledger',
        id: `${companyId}-led-exp-transport`,
        code: 'EXP_TRANSPORT_FLEET',
        name: 'Fleet Logistics & Fuel Payments',
        debit: '0.00',
        credit: '61000000.00',
        balance: '61000000.00',
        balanceSide: 'CREDIT',
      },
    ],
  };
}

export function getMockReceiptsAndPayments(companyId: string): ReceiptsAndPaymentsReport {
  return {
    period: {
      financialYearId: `${companyId}-fy-2026`,
      financialYearLabel: '2026',
      financialYearStatus: 'OPEN',
      from: '2026-04-01',
      to: '2026-10-07',
    },
    comparison: null,
    openingBalance: '41700000.00',
    openingSide: 'DEBIT',
    closingBalance: '87700000.00',
    closingSide: 'DEBIT',
    totals: {
      receipts: '287000000.00',
      payments: '241000000.00',
      difference: '46000000.00',
    },
    receipts: [
      {
        ledgerId: `${companyId}-led-rev-tour`,
        accountGroupId: `${companyId}-grp-dir-income`,
        code: 'REV_TOUR_PACKAGES',
        name: 'Tour Package Client Receipts',
        amount: '168000000.00',
      },
      {
        ledgerId: `${companyId}-led-rev-flight`,
        accountGroupId: `${companyId}-grp-dir-income`,
        code: 'REV_FLIGHT_TICKETS',
        name: 'International Flight Settlement Receipts',
        amount: '69000000.00',
      },
      {
        ledgerId: `${companyId}-led-rev-freight`,
        accountGroupId: `${companyId}-grp-dir-income`,
        code: 'REV_LOGISTICS_FREIGHT',
        name: 'Logistics Freight Cargo Receipts',
        amount: '50000000.00',
      },
    ],
    payments: [
      {
        ledgerId: `${companyId}-led-exp-salary`,
        accountGroupId: `${companyId}-grp-dir-exp`,
        code: 'EXP_SALARIES',
        name: 'Staff Salaries & Operations Wages',
        amount: '124000000.00',
      },
      {
        ledgerId: `${companyId}-led-exp-transport`,
        accountGroupId: `${companyId}-grp-dir-exp`,
        code: 'EXP_TRANSPORT_FLEET',
        name: 'Fleet Logistics, Fuel & Maintenance',
        amount: '61000000.00',
      },
      {
        ledgerId: `${companyId}-led-exp-rent`,
        accountGroupId: `${companyId}-grp-indir-exp`,
        code: 'EXP_OFFICE_RENT',
        name: 'Office Leases & Hub Rentals',
        amount: '32000000.00',
      },
      {
        ledgerId: `${companyId}-led-exp-marketing`,
        accountGroupId: `${companyId}-grp-indir-exp`,
        code: 'EXP_MARKETING_ADS',
        name: 'Marketing, Advertising & Software Licenses',
        amount: '24000000.00',
      },
    ],
  };
}

export function getMockOutstandings(companyId: string, side: 'DEBIT' | 'CREDIT' = 'DEBIT'): OutstandingsReport {
  if (side === 'DEBIT') {
    return {
      asOf: '2026-10-07',
      side: 'DEBIT',
      totals: {
        outstanding: '13500000.00',
        byBucket: {
          NOT_DUE: '4800000.00',
          '0_30': '4800000.00',
          '31_60': '8700000.00',
          '61_90': '0.00',
          OVER_90: '0.00',
        },
      },
      bills: [
        {
          billId: 'b-1',
          ledgerId: `${companyId}-led-cust-habtoor`,
          ledgerCode: 'CUST_AL_HABTOOR',
          ledgerName: 'Al Habtoor Travels LLC (Dubai)',
          reference: 'HAB-INV-441',
          billDate: '2026-09-15',
          dueDate: '2026-10-15',
          side: 'DEBIT',
          amount: '4800000.00',
          settled: '0.00',
          outstanding: '4800000.00',
          overdueDays: 0,
          bucket: '0_30',
        },
        {
          billId: 'b-2',
          ledgerId: `${companyId}-led-cust-royal`,
          ledgerCode: 'CUST_ROYAL_HOLIDAYS',
          ledgerName: 'Royal Holidays UK Ltd',
          reference: 'ROYAL-LDN-88',
          billDate: '2026-09-02',
          dueDate: '2026-10-02',
          side: 'DEBIT',
          amount: '3200000.00',
          settled: '0.00',
          outstanding: '3200000.00',
          overdueDays: 5,
          bucket: '31_60',
        },
        {
          billId: 'b-3',
          ledgerId: `${companyId}-led-cust-apex`,
          ledgerCode: 'CUST_APEX_LOGISTICS',
          ledgerName: 'Apex Global Logistics Corp',
          reference: 'APEX-CARGO-12',
          billDate: '2026-08-20',
          dueDate: '2026-09-20',
          side: 'DEBIT',
          amount: '5500000.00',
          settled: '0.00',
          outstanding: '5500000.00',
          overdueDays: 17,
          bucket: '31_60',
        },
      ],
    };
  }

  return {
    asOf: '2026-10-07',
    side: 'CREDIT',
    totals: {
      outstanding: '5250000.00',
      byBucket: {
        NOT_DUE: '2500000.00',
        '0_30': '5250000.00',
        '31_60': '0.00',
        '61_90': '0.00',
        OVER_90: '0.00',
      },
    },
    bills: [
      {
        billId: 'bv-1',
        ledgerId: `${companyId}-led-vend-emirates`,
        ledgerCode: 'VEND_EMIRATES_AIR',
        ledgerName: 'Emirates Airlines B2B Corporate',
        reference: 'AIR-99214',
        billDate: '2026-09-28',
        dueDate: '2026-10-28',
        side: 'CREDIT',
        amount: '2500000.00',
        settled: '0.00',
        outstanding: '2500000.00',
        overdueDays: 0,
        bucket: '0_30',
      },
      {
        billId: 'bv-2',
        ledgerId: `${companyId}-led-vend-marriott`,
        ledgerCode: 'VEND_MARRIOTT_RESORT',
        ledgerName: 'Marriott Luxury Hotel Suites B2B',
        reference: 'MARR-B2B-19',
        billDate: '2026-09-20',
        dueDate: '2026-10-20',
        side: 'CREDIT',
        amount: '1800000.00',
        settled: '0.00',
        outstanding: '1800000.00',
        overdueDays: 0,
        bucket: '0_30',
      },
      {
        billId: 'bv-3',
        ledgerId: `${companyId}-led-vend-petro`,
        ledgerCode: 'VEND_BHARAT_PETRO',
        ledgerName: 'Bharat Petroleum Fleet Cards',
        reference: 'PETRO-774',
        billDate: '2026-09-10',
        dueDate: '2026-10-10',
        side: 'CREDIT',
        amount: '950000.00',
        settled: '0.00',
        outstanding: '950000.00',
        overdueDays: 0,
        bucket: '0_30',
      },
    ],
  };
}

